[build-system]
requires = ['cython', 'numpy', 'setuptools<=75.7.0', 'pyqt5']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]

[project]
name = 'muondatalib'

version = "0.9.2b10"

requires-python = ">=3.8"
dependencies = ['numpy', 'h5py', 'plotly', 'cython', 'pyqt5', 'dash[testing]', 'dash_bootstrap_components', 'pyqtwebengine', 'dash_daq']
authors = [{name='Anthony Lim', email='anthony.lim@stfc.ac.uk'}]
description = 'Reading and writing for ISIS muon experiments.'
readme = 'README.md'
license = {text = 'BSD'}

